---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Release Drafter
        uses: release-drafter/release-drafter@73b95fa1c286dfd6802a4f949b07dad6149f2b0f # v7.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
